# Tendencias e Innovacion en Tecnologia Agricola (TEA)
tipodeDatos = input("Que tipos de datos salen en la consola 1.2.1 ? ")
print(tipodeDatos)
tipodeDatos = input("Que tipos de datos salen en la consola 1.2.2 ? ")
print(tipodeDatos)
tipodeDatos = input("Que tipos de datos sale en la consola 1.2.3 ? ")
print(tipodeDatos)
nombrecompleto = input (" Cual es tu nombre completo ? ")
print(nombrecompleto)
correo = input ("Cual es su correo ? ")
print(correo)
direccion = input ("Cual es la direccion de su repositorio de codigo fuente ? ")
print(direccion)
